global:
  # -- Sets an override for the suffix of the full name (Applies to current chart and all sub-charts)
  nameOverride: ""
  # -- Sets additional global annotations. Helm templates can be used.
  annotations: {}
  # -- Set additional global labels. Helm templates can be used.
  labels: {}

# -- Sets an override for the suffix of the full name (Applies to current chart only)
nameOverride: ""

ixExternalInterfacesConfigurationNames: []
  # - interface1
  # - interface2

controller:
  # -- Enable the controller.
  enabled: true
  # -- Set the controller type.
  # Valid options are: deployment | daemonset | statefulset
  type: deployment
