# This file only includes the default values that are applied.
# All values can be overridden per chart, in their values.yaml
# For Examples and Explanation view the "Values.yaml Explained" markdown file

global:
  nameOverride: ""
  annotations: {}
  labels: {}

nameOverride: ""

podAnnotations: {}

podLabels: {}

# TODO: docs
ixExternalInterfacesConfigurationNames: []
  # - interface1
  # - interface2

# TODO: docs
image:
  # -- Image repository
  repository:
  # -- Image tag
  tag:
  # -- Image pull policy
  pullPolicy: IfNotPresent

command: []

args: []

extraArgs: []

tty: false

stdin: false

# TODO: docs
podSecurityContext:
  runAsUser: 568
  runAsGroup: 568
  fsGroup: 568
  supplementalGroups: []
  fsGroupChangePolicy: OnRootMismatch

securityContext:
  privileged: false
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  runAsNonRoot: true
  capabilities:
    drop: []
    add: []

# -- Configure the lifecycle for the main container
lifecycle: {}

termination:
  # -- Configure the path at which the file to which the main container's termination message will be written.
  # [[ref](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#lifecycle-1)]
  messagePath:
  # -- Indicate how the main container's termination message should be populated.
  # Valid options are `File` and `FallbackToLogsOnError`.
  # [[ref](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#lifecycle-1)]
  messagePolicy:
  # -- Duration in seconds the pod needs to terminate gracefully
  # [[ref](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#lifecycle)]
  gracePeriodSeconds: 10

# -- Set the resource requests / limits for the main container.
resources:
  limits:
    cpu: 4000m
    memory: 8Gi
  requests:
    cpu: 10m
    memory: 50Mi

# -- Used to add SCALE GPU configuration
scaleGPU: {}  # TODO: Verify that this is the correct value returned from ref
  # gpu: 1

# -- Set specific NVIDIA Capabilities
nvidiaCaps:
  - all

# -- Injects some envs based on conditions that 99% of containers use
# See "ix.v1.common.container.fixedEnvs" for more info.
# TODO: Discuss the default
injectFixedEnvs: true

# -- Set Container Timezone
TZ: UTC

# -- Set the Process User ID (PUID) env-var separately
security:
  PUID: 568
  UMASK: 002

# -- Main environment variables. Helm Template enabled.
# Syntax options:
# A) TZ: UTC
# B) ENV_VAR: "{{ .Release.Name }}"
# C) ENV_VAR:
#      configMapKeyRef | secretKeyRef:
#        name: object-name | "{{ .Values.objectName }}"
#        key: key-name | "{{ .Values.some_key }}"
#        optional: false (ony with secretKeyRef)
env: {}
  # some_env: some_value
  # some_env2: some_value2

# -- Mainly used in the SCALE UI. Helm Template enabled.
envList: []
  # - name: SOME_ENV_VAR
  #   value: SOME_VALUE
  # - name: SOME_ENV_VAR2
  #   value: SOME_VALUE2

# Load envs from secret or configMap. Helm template enabled.
envFrom: []
#   - configMapRef:
#       name: config-map-name
#   - secretRef:
#       name: secret-name

controller:
  # -- Enable the controller.
  enabled: true
  # -- Set the controller type.
  # Valid options are: deployment | daemonset | statefulset
  type: deployment
  # -- Set labels on the deployment/statefulset/daemonset. Helm templates can be used.
  labels: {}
  # -- Set  annotations on the deployment/statefulset/daemonset. Helm templates can be used.
  annotations: {}
  # -- Revision history limit
  revisionHistoryLimit: 3
  # -- Number of desired pods
  replicas: 1
  # -- Set the controller upgrade strategy
  # For Deployments, valid values are Recreate (default) and RollingUpdate.
  # For StatefulSets, valid values are OnDelete and RollingUpdate (default).
  # DaemonSets ignore this.
  strategy: ""
  # -- Set rollingUpdate strategies
  rollingUpdate:
    # -- Set deployment RollingUpdate max unavailable
    unavailable:
    # -- Set deployment RollingUpdate max surge
    surge:
    # -- Set statefulset RollingUpdate partition
    partition:

# -- Configure the services for the chart here.
# Additional services can be added by adding a dictionary key similar to the 'main' service.
# @default -- See below
service:
  main:
    # -- Enables or disables the service
    enabled: true
    # enabled: false
    # -- Configure the Service port information here.
    # Additional ports can be added by adding a dictionary key similar to the 'main' port.
    # @default -- See below
    ports:
      main:
        # -- Enables or disables the port
        enabled: true
        # enabled: false
        # -- Make this the primary port (used in probes, notes, etc...)
        # If there is more than 1 service, make sure that only 1 port is marked as primary.
        primary: true
        # -- The port number (Default port is required if enabled: true)
        port: 999999  #TODO:
        # -- Port protocol.
        # Support values are `HTTP`, `HTTPS`, `TCP` and `UDP`.
        # HTTPS and HTTPS spawn a TCP service and get used for internal URL and name generation
        protocol: HTTP
        # -- Specify a service targetPort if you wish to differ the service port from the application port.
        # If `targetPort` is specified, this port number is used in the container definition instead of
        # the `port` value. Therefore named ports are not supported for this field.
        targetPort:
        # -- Specify the nodePort value NodePort service types.
        # [[ref]](https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport)
        nodePort:

# -- Define probes. Helm template enabled on, path, port, httpHeader values
probes:
  # -- Liveness probe configuration
  # @default -- See below
  liveness:
    # -- Enable the liveness probe
    enabled: true
    # -- Set this to `true` if you wish to specify your own livenessProbe
    custom: false
    # -- sets the probe type when not using a custom probe
    # @default -- "TCP"
    type: AUTO
    # -- If an HTTP probe is used (default for HTTP/HTTPS services) this path is used. Helm tpl enabled
    # @default -- "/"
    path: "/"
    # -- If an exec is used, it sets the commands. Helm tpl enabled.
    command: []
    # -- If an HTTP probe is used (default for HTTP/HTTPS services) this headers are used
    httpHeaders: {}
      # some_header: some_value
    # -- The spec field contains the values for the default livenessProbe.
    # If you selected `custom: true`, this field holds the definition of the livenessProbe.
    # @default -- See below
    spec:
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 5

  # -- Redainess probe configuration
  # @default -- See below
  readiness:
    # -- Enable the readiness probe
    enabled: true
    # -- Set this to `true` if you wish to specify your own readinessProbe
    custom: false
    # -- sets the probe type when not using a custom probe
    # @default -- "TCP"
    type: AUTO
    # -- If a HTTP probe is used (default for HTTP/HTTPS services) this path is used
    # @default -- "/"
    path: "/"
    # -- If an exec is used, it sets the commands. Helm tpl enabled.
    command: []
    # -- The spec field contains the values for the default readinessProbe.
    # If you selected `custom: true`, this field holds the definition of the readinessProbe.
    # @default -- See below
    spec:
      initialDelaySeconds: 10
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 5

  # -- Startup probe configuration
  # @default -- See below
  startup:
    # -- Enable the startup probe
    enabled: true
    # -- Set this to `true` if you wish to specify your own startupProbe
    custom: false
    # -- sets the probe type when not using a custom probe
    # @default -- "TCP"
    type: AUTO
    # -- If a HTTP probe is used (default for HTTP/HTTPS services) this path is used
    # @default -- "/"
    path: "/"
    # -- If an exec is used, it sets the commands. Helm tpl enabled.
    command: []
    # -- set to override the default port without using custom startupProbe
    # Accepts TPL
    # @default -- ""
    port: ""
    # -- The spec field contains the values for the default startupProbe.
    # If you selected `custom: true`, this field holds the definition of the startupProbe.
    # @default -- See below
    spec:
      initialDelaySeconds: 10
      timeoutSeconds: 2
      ## This means it has a maximum of 5*30=150 seconds to start up before it fails
      periodSeconds: 5
      failureThreshold: 60

# -- Configure persistence for the chart here.
# Additional items can be added by adding a dictionary key similar to the 'pvc-example' key.
# @default -- See below
persistence:
  # TODO: Move examples to documentation instead of here
  pvc-example:
    # -- Enables or disables the persistence item
    enabled: false
    # -- Sets the persistence type
    # Valid options are: pvc | emptyDir | secret | configMap | hostPath | custom
    type: pvc
    # -- Sets an override for the suffix of this volume
    nameOverride: ""
    annotationsList: []
    # - name: somename
    #   value: somevalue
    # -- Add annotations to PVC object
    annotations: {}
    labelsList: []
    # - name: somename
    #   value: somevalue
    # -- Set labels on the deployment/statefulset/daemonset
    # -- Provide additional labels which may be required.
    # -- Add labels to PVC object
    labels: {}
    # -- If you want to reuse an existing claim, the name of the existing PVC can be passed here.
    existingClaim: ""
    # -- force the complete PVC name
    # Will not add any prefix or suffix
    forceName: ""
    # -- Where to mount the volume in the main container.
    mountPath:  # /config
    # -- Specify if the volume should be mounted read-only.
    readOnly: false
    # -- Creates the volume but skips the volumeMount
    noMount: false

  # -- Example of a hostPath mount
  # [[ref]]https://kubernetes.io/docs/concepts/storage/volumes/#hostpath)
  # @default -- See below
  host-dev:
    enabled: false
    type: hostPath
    # -- Which path on the host should be mounted.
    hostPath: /dev
    # -- Automatic set permissions using chown and chmod
    setPermissions: false
    # -- Where to mount the path in the main container.
    # Defaults to the value of `hostPath`
    mountPath: # /myDev
    # -- Specifying a hostPathType adds a check before trying to mount the path.
    # See Kubernetes documentation for options.
    hostPathType: ""
    # -- Specify if the path should be mounted read-only.
    readOnly: true

  # -- Example of a configmap mount
  # @default -- See below
  configmap-example:
    enabled: false
    type: configMap
    # -- Specify the name of the configmap object to be mounted. Helm templates can be used.
    objectName: myconfig-map
    # -- Where to mount the volume in the main container.
    # Defaults to `/<name_of_the_volume>`,
    # setting to '-' creates the volume but disables the volumeMount.
    mountPath:  # /custom-mount
    # -- Specify if the volume should be mounted read-only.
    readOnly: false

  # -- Example of a secret mount
  # @default -- See below
  secret-example:
    enabled: false
    type: secret
    # -- Specify the name of the secret object to be mounted. Helm templates can be used.
    objectName: mysecret
    # -- Where to mount the volume in the main container.
    # Defaults to `/<name_of_the_volume>`,
    # setting to '-' creates the volume but disables the volumeMount.
    mountPath: # /custom-mount
    # -- Specify if the volume should be mounted read-only.
    readOnly: false
    # -- define the default mount mode for the secret
    defaultMode: 0644
    # -- Define the secret items to be mounted
    items:
      - key: username
        path: my-group/my-username

  # -- Example of a nfs mount
  # @default -- See below
  nfs-example:
    enabled: false
    type: nfs
    # -- Specify the name of the secret object to be mounted
    server: 192.168.10.10
    # -- define the default mount path on the nfs server
    path: "/somepath"
    # -- Where to mount the volume in the main container.
    # Defaults to `/<name_of_the_volume>`,
    # setting to '-' creates the volume but disables the volumeMount.
    mountPath:  # /custom-mount
    # -- Specify if the volume should be mounted read-only.
    readOnly: false

  # -- Create an emptyDir volume to for /dev/shm
  # [[ref]]https://kubernetes.io/docs/concepts/storage/volumes/#emptydir)
  # @default -- See below
  shm:
    # TODO: discuss if we enable it by default
    enabled: false
    type: emptyDir
    mountPath: /dev/shm
    # -- Set the medium to "Memory" to mount a tmpfs (RAM-backed filesystem) instead
    # of the storage medium that backs the node.
    medium: Memory
    # -- If the `SizeMemoryBackedVolumes` feature gate is enabled, you can
    # specify a size for memory backed volumes.
    sizeLimit: # 1Gi

  # -- Create an emptyDir volume to share between all containers for temporary storage
  # @default -- See below
  temp:
    # TODO: discuss if we enable it by default
    enabled: false
    type: emptyDir
    mountPath: /tmp
    # -- Set the medium to "Memory" to mount a tmpfs (RAM-backed filesystem) instead
    # of the storage medium that backs the node.
    medium:  # Memory
    # -- If the `SizeMemoryBackedVolumes` feature gate is enabled, you can
    # specify a size for memory backed volumes.
    sizeLimit: # 1Gi

  # -- Create an emptyDir volume to share between all containers
  # [[ref]]https://kubernetes.io/docs/concepts/storage/volumes/#emptydir)
  # @default -- See below
  varlogs:
    # TODO: discuss if we enable it by default
    enabled: false
    type: emptyDir
    mountPath: /var/logs
    # -- Set the medium to "Memory" to mount a tmpfs (RAM-backed filesystem) instead
    # of the storage medium that backs the node.
    medium:  # Memory
    # -- If the `SizeMemoryBackedVolumes` feature gate is enabled, you can
    # specify a size for memory backed volumes.
    sizeLimit: # 1Gi

  # -- Create an emptyDir volume to share between all containers
  # [[ref]]https://kubernetes.io/docs/concepts/storage/volumes/#emptydir)
  # @default -- See below
  shared:
    # TODO: discuss if we enable it by default
    enabled: false
    type: emptyDir
    mountPath: /shared
    # -- Set the medium to "Memory" to mount a tmpfs (RAM-backed filesystem) instead
    # of the storage medium that backs the node.
    medium:  # Memory
    # -- If the `SizeMemoryBackedVolumes` feature gate is enabled, you can
    # specify a size for memory backed volumes.
    sizeLimit:  # 1Gi

# -- Used in conjunction with `controller.type: statefulset` to create individual disks for each instance.
volumeClaimTemplates: {}
# data:
#   mountPath: /data
#   accessMode: "ReadWriteOnce"
#   size: 1Gi
