image:
  repository: traefik/whoami
  pullPolicy: IfNotPresent
  tag: latest

alpineImage:
  repository: alpine
  tag: latest
  pullPolicy: IfNotPresent

service:
  main:
    ports:
      main:
        protocol: HTTP
        port: 8080

args:
  - --port
  - "8080"

additionalContainers:
  some-name:
    imageSelector: image
    args:
      - --port
      - "8081"
    probes:
      liveness:
        enabled: true
        port: 8081
        type: http
        path: /
      readiness:
        enabled: true
        port: 8081
        type: http
        path: /
      startup:
        enabled: true
        port: 8081
        type: http
        path: /
initContainers:
  some-name:
    imageSelector: alpineImage
    command:
      - /bin/sh
      - -c
      - echo "Hello World"
systemContainers:
  some-name:
    imageSelector: alpineImage
    command:
      - /bin/sh
      - -c
      - echo "Hello World"
installContainers:
  some-name:
    imageSelector: alpineImage
    command:
      - /bin/sh
      - -c
      - echo "Hello World"

probes:
  liveness:
    enabled: true
  readiness:
    enabled: true
  startup:
    enabled: true
