image:
  repository: traefik/whoami
  pullPolicy: IfNotPresent
  tag: latest

someImage:
  repository: traefik/whoami
  tag: latest
  pullPolicy: Never

service:
  main:
    ports:
      main:
        protocol: HTTP
        port: 8080

args:
  - --port
  - "8080"

additionalContainers:
  some-name:
    imageSelector: someImage
    pullPolicy: Never
    args:
      - --port
      - "8081"
    probes:
      liveness:
        enabled: true
        port: 8081
        type: http
        path: /
      readiness:
        enabled: true
        port: 8081
        type: http
        path: /
      startup:
        enabled: true
        port: 8081
        type: http
        path: /
initContainers:
  some-name:
    imageSelector: someImage
    pullPolicy: Never
    command:
      - /bin/sh
      - -c
      - echo "Hello World"
systemContainers:
  some-name:
    imageSelector: someImage
    pullPolicy: Never
    command:
      - /bin/sh
      - -c
      - echo "Hello World"
installContainers:
  some-name:
    imageSelector: someImage
    pullPolicy: Never
    command:
      - /bin/sh
      - -c
      - echo "Hello World"

probes:
  liveness:
    enabled: true
  readiness:
    enabled: true
  startup:
    enabled: true
