image:
  repository: traefik/whoami
  pullPolicy: IfNotPresent
  tag: latest

controller:
  # -- Enable the controller.
  enabled: true
  # -- Set the controller type.
  # Valid options are: deployment | daemonset | statefulset
  type: StatefulSet
  # -- Number of desired pods
  replicas: 2

volumeClaimTemplates:
  test:
    mountPath: /test
    accessMode: "ReadWriteOnce"
    size: 1Gi

service:
  main:
    ports:
      main:
        protocol: HTTP
        port: 8080

args:
  - --port
  - "8080"

probes:
  liveness:
    enabled: true
  readiness:
    enabled: true
  startup:
    enabled: true
