service:
  main:
    ports:
      main:
        port: 65535

initImage:
  repository: something
  tag: somethingeles


# env:
#   TZ: tsd


# TODO: Unittests
# initContainers:
#   init-db:
#     imageSelector: initImage
#     pullPolicy: Always
#     tty: true
#     stdin: true
# installContainer:
#   ainit-db:
#     imageSelector: initImage
#     pullPolicy: Always
#     tty: true
#     stdin: true
    # command:
    #   - this
    #   - is
    #   - |
    #     a test
    # args:
    #   - this args
    #   - is
    #   - |
    #     a test
    # extraArgs:
    #   - this extraargs
    #   - is
    #   - |
    #     a test
    # termination:
    #   messagePath: something
    #   messagePolicy: FallbackToLogsOnError
    # scaleGPU:
    #   gpu.intel.com/i915: "1"
    # resources:
    #   limits:
    #     cpu: 1000m
    #     memory: 2Gi
    #   requests:
    #     cpu: 10m
    #     memory: 10Mi
    # env:
    #   key: value
    #   test: tasdt
    #   blbla: tasd
    # envFrom:
    #   - configMapRef:
    #       name: omething
    #   - secretRef:
    #       name: omething
    # envList:
    #   # - name: blbla
    #   #   value: tasd
    #   - name: blbla23
    #     value: tasd234
